# Generated by Django 3.2.4 on 2021-06-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='years_employeed',
            new_name='years_employed',
        ),
    ]
