# Generated by Django 3.2.4 on 2021-06-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_years_employeed_profile_years_employed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_name', models.CharField(max_length=255)),
                ('employees', models.ManyToManyField(to='projects.Employee')),
            ],
        ),
    ]
